/**
 *
 *  Event.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace dnd
{
class Effect;
class Item;
class Player;
class Spell;

class Event
{
  public:
    struct Cols
    {
        static const std::string _Id;
        static const std::string _Name;
        static const std::string _Description;
        static const std::string _Duration;
        static const std::string _EffectId;
        static const std::string _Amount;
        static const std::string _PlayerId;
        static const std::string _ItemId;
        static const std::string _SpellId;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Event(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Event(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Event(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Event() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column Id  */
    ///Get the value of the column Id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column Id
    void setId(const int32_t &pId) noexcept;

    /**  For column Name  */
    ///Get the value of the column Name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column Name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;

    /**  For column Description  */
    ///Get the value of the column Description, returns the default value if the column is null
    const std::string &getValueOfDescription() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDescription() const noexcept;
    ///Set the value of the column Description
    void setDescription(const std::string &pDescription) noexcept;
    void setDescription(std::string &&pDescription) noexcept;

    /**  For column Duration  */
    ///Get the value of the column Duration, returns the default value if the column is null
    const int16_t &getValueOfDuration() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int16_t> &getDuration() const noexcept;
    ///Set the value of the column Duration
    void setDuration(const int16_t &pDuration) noexcept;
    void setDurationToNull() noexcept;

    /**  For column EffectId  */
    ///Get the value of the column EffectId, returns the default value if the column is null
    const int32_t &getValueOfEffectid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getEffectid() const noexcept;
    ///Set the value of the column EffectId
    void setEffectid(const int32_t &pEffectid) noexcept;
    void setEffectidToNull() noexcept;

    /**  For column Amount  */
    ///Get the value of the column Amount, returns the default value if the column is null
    const int16_t &getValueOfAmount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int16_t> &getAmount() const noexcept;
    ///Set the value of the column Amount
    void setAmount(const int16_t &pAmount) noexcept;
    void setAmountToNull() noexcept;

    /**  For column PlayerId  */
    ///Get the value of the column PlayerId, returns the default value if the column is null
    const int32_t &getValueOfPlayerid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getPlayerid() const noexcept;
    ///Set the value of the column PlayerId
    void setPlayerid(const int32_t &pPlayerid) noexcept;
    void setPlayeridToNull() noexcept;

    /**  For column ItemId  */
    ///Get the value of the column ItemId, returns the default value if the column is null
    const int32_t &getValueOfItemid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getItemid() const noexcept;
    ///Set the value of the column ItemId
    void setItemid(const int32_t &pItemid) noexcept;
    void setItemidToNull() noexcept;

    /**  For column SpellId  */
    ///Get the value of the column SpellId, returns the default value if the column is null
    const int32_t &getValueOfSpellid() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getSpellid() const noexcept;
    ///Set the value of the column SpellId
    void setSpellid(const int32_t &pSpellid) noexcept;
    void setSpellidToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 9;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    void getPlayer(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Player)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    void getEffect(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Effect)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    void getSpell(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Spell)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    void getItem(const drogon::orm::DbClientPtr &clientPtr,
                 const std::function<void(Item)> &rcb,
                 const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Event>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Event>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> description_;
    std::shared_ptr<int16_t> duration_;
    std::shared_ptr<int32_t> effectid_;
    std::shared_ptr<int16_t> amount_;
    std::shared_ptr<int32_t> playerid_;
    std::shared_ptr<int32_t> itemid_;
    std::shared_ptr<int32_t> spellid_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[9]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where Id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where Id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "Id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "Name,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "Description,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "Duration,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "EffectId,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "Amount,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "PlayerId,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "ItemId,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "SpellId,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        sql +="default,";
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace dnd
} // namespace drogon_model
