/**
 *
 *  Player.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Player.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::dnd;

const std::string Player::Cols::_Id = "Id";
const std::string Player::Cols::_Name = "Name";
const std::string Player::Cols::_Race = "Race";
const std::string Player::Cols::_Class = "Class";
const std::string Player::Cols::_ArmorClass = "ArmorClass";
const std::string Player::Cols::_Str = "Str";
const std::string Player::Cols::_Con = "Con";
const std::string Player::Cols::_Dex = "Dex";
const std::string Player::Cols::_Int = "Int";
const std::string Player::Cols::_Wis = "Wis";
const std::string Player::Cols::_Cha = "Cha";
const std::string Player::Cols::_Fortitude = "Fortitude";
const std::string Player::Cols::_Reflex = "Reflex";
const std::string Player::Cols::_Will = "Will";
const std::string Player::Cols::_RolledHp = "RolledHp";
const std::string Player::Cols::_Xp = "Xp";
const std::string Player::Cols::_Load = "Load";
const std::string Player::primaryKeyName = "Id";
const bool Player::hasPrimaryKey = true;
const std::string Player::tableName = "player";

const std::vector<typename Player::MetaData> Player::metaData_={
{"Id","int32_t","int(11)",4,1,1,1},
{"Name","std::string","varchar(100)",100,0,0,0},
{"Race","std::string","varchar(100)",100,0,0,0},
{"Class","std::string","varchar(100)",100,0,0,0},
{"ArmorClass","int16_t","smallint(6)",2,0,0,1},
{"Str","int16_t","smallint(6)",2,0,0,1},
{"Con","int16_t","smallint(6)",2,0,0,1},
{"Dex","int16_t","smallint(6)",2,0,0,1},
{"Int","int16_t","smallint(6)",2,0,0,1},
{"Wis","int16_t","smallint(6)",2,0,0,1},
{"Cha","int16_t","smallint(6)",2,0,0,1},
{"Fortitude","int16_t","smallint(6)",2,0,0,1},
{"Reflex","int16_t","smallint(6)",2,0,0,1},
{"Will","int16_t","smallint(6)",2,0,0,1},
{"RolledHp","int16_t","smallint(6)",2,0,0,1},
{"Xp","int32_t","int(11)",4,0,0,1},
{"Load","int16_t","smallint(6)",2,0,0,1}
};
const std::string &Player::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Player::Player(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["Id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["Id"].as<int32_t>());
        }
        if(!r["Name"].isNull())
        {
            name_=std::make_shared<std::string>(r["Name"].as<std::string>());
        }
        if(!r["Race"].isNull())
        {
            race_=std::make_shared<std::string>(r["Race"].as<std::string>());
        }
        if(!r["Class"].isNull())
        {
            class_=std::make_shared<std::string>(r["Class"].as<std::string>());
        }
        if(!r["ArmorClass"].isNull())
        {
            armorclass_=std::make_shared<int16_t>(r["ArmorClass"].as<int16_t>());
        }
        if(!r["Str"].isNull())
        {
            str_=std::make_shared<int16_t>(r["Str"].as<int16_t>());
        }
        if(!r["Con"].isNull())
        {
            con_=std::make_shared<int16_t>(r["Con"].as<int16_t>());
        }
        if(!r["Dex"].isNull())
        {
            dex_=std::make_shared<int16_t>(r["Dex"].as<int16_t>());
        }
        if(!r["Int"].isNull())
        {
            int_=std::make_shared<int16_t>(r["Int"].as<int16_t>());
        }
        if(!r["Wis"].isNull())
        {
            wis_=std::make_shared<int16_t>(r["Wis"].as<int16_t>());
        }
        if(!r["Cha"].isNull())
        {
            cha_=std::make_shared<int16_t>(r["Cha"].as<int16_t>());
        }
        if(!r["Fortitude"].isNull())
        {
            fortitude_=std::make_shared<int16_t>(r["Fortitude"].as<int16_t>());
        }
        if(!r["Reflex"].isNull())
        {
            reflex_=std::make_shared<int16_t>(r["Reflex"].as<int16_t>());
        }
        if(!r["Will"].isNull())
        {
            will_=std::make_shared<int16_t>(r["Will"].as<int16_t>());
        }
        if(!r["RolledHp"].isNull())
        {
            rolledhp_=std::make_shared<int16_t>(r["RolledHp"].as<int16_t>());
        }
        if(!r["Xp"].isNull())
        {
            xp_=std::make_shared<int32_t>(r["Xp"].as<int32_t>());
        }
        if(!r["Load"].isNull())
        {
            load_=std::make_shared<int16_t>(r["Load"].as<int16_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 17 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            name_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            race_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            class_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            armorclass_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            str_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            con_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            dex_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            int_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            wis_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            cha_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            fortitude_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            reflex_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            will_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            rolledhp_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
        index = offset + 15;
        if(!r[index].isNull())
        {
            xp_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 16;
        if(!r[index].isNull())
        {
            load_=std::make_shared<int16_t>(r[index].as<int16_t>());
        }
    }

}

Player::Player(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 17)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            race_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            class_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            armorclass_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            str_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            con_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            dex_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            int_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            wis_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            cha_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            fortitude_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            reflex_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            will_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            rolledhp_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[14]].asInt64());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            xp_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[15]].asInt64());
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            load_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[16]].asInt64());
        }
    }
}

Player::Player(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("Id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["Id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["Id"].asInt64());
        }
    }
    if(pJson.isMember("Name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["Name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["Name"].asString());
        }
    }
    if(pJson.isMember("Race"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["Race"].isNull())
        {
            race_=std::make_shared<std::string>(pJson["Race"].asString());
        }
    }
    if(pJson.isMember("Class"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["Class"].isNull())
        {
            class_=std::make_shared<std::string>(pJson["Class"].asString());
        }
    }
    if(pJson.isMember("ArmorClass"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["ArmorClass"].isNull())
        {
            armorclass_=std::make_shared<int16_t>((int16_t)pJson["ArmorClass"].asInt64());
        }
    }
    if(pJson.isMember("Str"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["Str"].isNull())
        {
            str_=std::make_shared<int16_t>((int16_t)pJson["Str"].asInt64());
        }
    }
    if(pJson.isMember("Con"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["Con"].isNull())
        {
            con_=std::make_shared<int16_t>((int16_t)pJson["Con"].asInt64());
        }
    }
    if(pJson.isMember("Dex"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["Dex"].isNull())
        {
            dex_=std::make_shared<int16_t>((int16_t)pJson["Dex"].asInt64());
        }
    }
    if(pJson.isMember("Int"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["Int"].isNull())
        {
            int_=std::make_shared<int16_t>((int16_t)pJson["Int"].asInt64());
        }
    }
    if(pJson.isMember("Wis"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["Wis"].isNull())
        {
            wis_=std::make_shared<int16_t>((int16_t)pJson["Wis"].asInt64());
        }
    }
    if(pJson.isMember("Cha"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["Cha"].isNull())
        {
            cha_=std::make_shared<int16_t>((int16_t)pJson["Cha"].asInt64());
        }
    }
    if(pJson.isMember("Fortitude"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["Fortitude"].isNull())
        {
            fortitude_=std::make_shared<int16_t>((int16_t)pJson["Fortitude"].asInt64());
        }
    }
    if(pJson.isMember("Reflex"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["Reflex"].isNull())
        {
            reflex_=std::make_shared<int16_t>((int16_t)pJson["Reflex"].asInt64());
        }
    }
    if(pJson.isMember("Will"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["Will"].isNull())
        {
            will_=std::make_shared<int16_t>((int16_t)pJson["Will"].asInt64());
        }
    }
    if(pJson.isMember("RolledHp"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["RolledHp"].isNull())
        {
            rolledhp_=std::make_shared<int16_t>((int16_t)pJson["RolledHp"].asInt64());
        }
    }
    if(pJson.isMember("Xp"))
    {
        dirtyFlag_[15]=true;
        if(!pJson["Xp"].isNull())
        {
            xp_=std::make_shared<int32_t>((int32_t)pJson["Xp"].asInt64());
        }
    }
    if(pJson.isMember("Load"))
    {
        dirtyFlag_[16]=true;
        if(!pJson["Load"].isNull())
        {
            load_=std::make_shared<int16_t>((int16_t)pJson["Load"].asInt64());
        }
    }
}

void Player::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 17)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            name_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            race_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            class_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            armorclass_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            str_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            con_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            dex_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            int_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            wis_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            cha_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            fortitude_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            reflex_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            will_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            rolledhp_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[14]].asInt64());
        }
    }
    if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
    {
        dirtyFlag_[15] = true;
        if(!pJson[pMasqueradingVector[15]].isNull())
        {
            xp_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[15]].asInt64());
        }
    }
    if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
    {
        dirtyFlag_[16] = true;
        if(!pJson[pMasqueradingVector[16]].isNull())
        {
            load_=std::make_shared<int16_t>((int16_t)pJson[pMasqueradingVector[16]].asInt64());
        }
    }
}

void Player::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("Id"))
    {
        if(!pJson["Id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["Id"].asInt64());
        }
    }
    if(pJson.isMember("Name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["Name"].isNull())
        {
            name_=std::make_shared<std::string>(pJson["Name"].asString());
        }
    }
    if(pJson.isMember("Race"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["Race"].isNull())
        {
            race_=std::make_shared<std::string>(pJson["Race"].asString());
        }
    }
    if(pJson.isMember("Class"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["Class"].isNull())
        {
            class_=std::make_shared<std::string>(pJson["Class"].asString());
        }
    }
    if(pJson.isMember("ArmorClass"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["ArmorClass"].isNull())
        {
            armorclass_=std::make_shared<int16_t>((int16_t)pJson["ArmorClass"].asInt64());
        }
    }
    if(pJson.isMember("Str"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["Str"].isNull())
        {
            str_=std::make_shared<int16_t>((int16_t)pJson["Str"].asInt64());
        }
    }
    if(pJson.isMember("Con"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["Con"].isNull())
        {
            con_=std::make_shared<int16_t>((int16_t)pJson["Con"].asInt64());
        }
    }
    if(pJson.isMember("Dex"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["Dex"].isNull())
        {
            dex_=std::make_shared<int16_t>((int16_t)pJson["Dex"].asInt64());
        }
    }
    if(pJson.isMember("Int"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["Int"].isNull())
        {
            int_=std::make_shared<int16_t>((int16_t)pJson["Int"].asInt64());
        }
    }
    if(pJson.isMember("Wis"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["Wis"].isNull())
        {
            wis_=std::make_shared<int16_t>((int16_t)pJson["Wis"].asInt64());
        }
    }
    if(pJson.isMember("Cha"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["Cha"].isNull())
        {
            cha_=std::make_shared<int16_t>((int16_t)pJson["Cha"].asInt64());
        }
    }
    if(pJson.isMember("Fortitude"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["Fortitude"].isNull())
        {
            fortitude_=std::make_shared<int16_t>((int16_t)pJson["Fortitude"].asInt64());
        }
    }
    if(pJson.isMember("Reflex"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["Reflex"].isNull())
        {
            reflex_=std::make_shared<int16_t>((int16_t)pJson["Reflex"].asInt64());
        }
    }
    if(pJson.isMember("Will"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["Will"].isNull())
        {
            will_=std::make_shared<int16_t>((int16_t)pJson["Will"].asInt64());
        }
    }
    if(pJson.isMember("RolledHp"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["RolledHp"].isNull())
        {
            rolledhp_=std::make_shared<int16_t>((int16_t)pJson["RolledHp"].asInt64());
        }
    }
    if(pJson.isMember("Xp"))
    {
        dirtyFlag_[15] = true;
        if(!pJson["Xp"].isNull())
        {
            xp_=std::make_shared<int32_t>((int32_t)pJson["Xp"].asInt64());
        }
    }
    if(pJson.isMember("Load"))
    {
        dirtyFlag_[16] = true;
        if(!pJson["Load"].isNull())
        {
            load_=std::make_shared<int16_t>((int16_t)pJson["Load"].asInt64());
        }
    }
}

const int32_t &Player::getValueOfId() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Player::getId() const noexcept
{
    return id_;
}
void Player::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Player::PrimaryKeyType & Player::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Player::getValueOfName() const noexcept
{
    const static std::string defaultValue = std::string();
    if(name_)
        return *name_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Player::getName() const noexcept
{
    return name_;
}
void Player::setName(const std::string &pName) noexcept
{
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[1] = true;
}
void Player::setName(std::string &&pName) noexcept
{
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[1] = true;
}
void Player::setNameToNull() noexcept
{
    name_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Player::getValueOfRace() const noexcept
{
    const static std::string defaultValue = std::string();
    if(race_)
        return *race_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Player::getRace() const noexcept
{
    return race_;
}
void Player::setRace(const std::string &pRace) noexcept
{
    race_ = std::make_shared<std::string>(pRace);
    dirtyFlag_[2] = true;
}
void Player::setRace(std::string &&pRace) noexcept
{
    race_ = std::make_shared<std::string>(std::move(pRace));
    dirtyFlag_[2] = true;
}
void Player::setRaceToNull() noexcept
{
    race_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Player::getValueOfClass() const noexcept
{
    const static std::string defaultValue = std::string();
    if(class_)
        return *class_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Player::getClass() const noexcept
{
    return class_;
}
void Player::setClass(const std::string &pClass) noexcept
{
    class_ = std::make_shared<std::string>(pClass);
    dirtyFlag_[3] = true;
}
void Player::setClass(std::string &&pClass) noexcept
{
    class_ = std::make_shared<std::string>(std::move(pClass));
    dirtyFlag_[3] = true;
}
void Player::setClassToNull() noexcept
{
    class_.reset();
    dirtyFlag_[3] = true;
}

const int16_t &Player::getValueOfArmorclass() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(armorclass_)
        return *armorclass_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getArmorclass() const noexcept
{
    return armorclass_;
}
void Player::setArmorclass(const int16_t &pArmorclass) noexcept
{
    armorclass_ = std::make_shared<int16_t>(pArmorclass);
    dirtyFlag_[4] = true;
}

const int16_t &Player::getValueOfStr() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(str_)
        return *str_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getStr() const noexcept
{
    return str_;
}
void Player::setStr(const int16_t &pStr) noexcept
{
    str_ = std::make_shared<int16_t>(pStr);
    dirtyFlag_[5] = true;
}

const int16_t &Player::getValueOfCon() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(con_)
        return *con_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getCon() const noexcept
{
    return con_;
}
void Player::setCon(const int16_t &pCon) noexcept
{
    con_ = std::make_shared<int16_t>(pCon);
    dirtyFlag_[6] = true;
}

const int16_t &Player::getValueOfDex() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(dex_)
        return *dex_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getDex() const noexcept
{
    return dex_;
}
void Player::setDex(const int16_t &pDex) noexcept
{
    dex_ = std::make_shared<int16_t>(pDex);
    dirtyFlag_[7] = true;
}

const int16_t &Player::getValueOfInt() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(int_)
        return *int_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getInt() const noexcept
{
    return int_;
}
void Player::setInt(const int16_t &pInt) noexcept
{
    int_ = std::make_shared<int16_t>(pInt);
    dirtyFlag_[8] = true;
}

const int16_t &Player::getValueOfWis() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(wis_)
        return *wis_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getWis() const noexcept
{
    return wis_;
}
void Player::setWis(const int16_t &pWis) noexcept
{
    wis_ = std::make_shared<int16_t>(pWis);
    dirtyFlag_[9] = true;
}

const int16_t &Player::getValueOfCha() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(cha_)
        return *cha_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getCha() const noexcept
{
    return cha_;
}
void Player::setCha(const int16_t &pCha) noexcept
{
    cha_ = std::make_shared<int16_t>(pCha);
    dirtyFlag_[10] = true;
}

const int16_t &Player::getValueOfFortitude() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(fortitude_)
        return *fortitude_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getFortitude() const noexcept
{
    return fortitude_;
}
void Player::setFortitude(const int16_t &pFortitude) noexcept
{
    fortitude_ = std::make_shared<int16_t>(pFortitude);
    dirtyFlag_[11] = true;
}

const int16_t &Player::getValueOfReflex() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(reflex_)
        return *reflex_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getReflex() const noexcept
{
    return reflex_;
}
void Player::setReflex(const int16_t &pReflex) noexcept
{
    reflex_ = std::make_shared<int16_t>(pReflex);
    dirtyFlag_[12] = true;
}

const int16_t &Player::getValueOfWill() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(will_)
        return *will_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getWill() const noexcept
{
    return will_;
}
void Player::setWill(const int16_t &pWill) noexcept
{
    will_ = std::make_shared<int16_t>(pWill);
    dirtyFlag_[13] = true;
}

const int16_t &Player::getValueOfRolledhp() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(rolledhp_)
        return *rolledhp_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getRolledhp() const noexcept
{
    return rolledhp_;
}
void Player::setRolledhp(const int16_t &pRolledhp) noexcept
{
    rolledhp_ = std::make_shared<int16_t>(pRolledhp);
    dirtyFlag_[14] = true;
}

const int32_t &Player::getValueOfXp() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(xp_)
        return *xp_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Player::getXp() const noexcept
{
    return xp_;
}
void Player::setXp(const int32_t &pXp) noexcept
{
    xp_ = std::make_shared<int32_t>(pXp);
    dirtyFlag_[15] = true;
}

const int16_t &Player::getValueOfLoad() const noexcept
{
    const static int16_t defaultValue = int16_t();
    if(load_)
        return *load_;
    return defaultValue;
}
const std::shared_ptr<int16_t> &Player::getLoad() const noexcept
{
    return load_;
}
void Player::setLoad(const int16_t &pLoad) noexcept
{
    load_ = std::make_shared<int16_t>(pLoad);
    dirtyFlag_[16] = true;
}

void Player::updateId(const uint64_t id)
{
    id_ = std::make_shared<int32_t>(static_cast<int32_t>(id));
}

const std::vector<std::string> &Player::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "Name",
        "Race",
        "Class",
        "ArmorClass",
        "Str",
        "Con",
        "Dex",
        "Int",
        "Wis",
        "Cha",
        "Fortitude",
        "Reflex",
        "Will",
        "RolledHp",
        "Xp",
        "Load"
    };
    return inCols;
}

void Player::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRace())
        {
            binder << getValueOfRace();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getClass())
        {
            binder << getValueOfClass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getArmorclass())
        {
            binder << getValueOfArmorclass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStr())
        {
            binder << getValueOfStr();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCon())
        {
            binder << getValueOfCon();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDex())
        {
            binder << getValueOfDex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getInt())
        {
            binder << getValueOfInt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getWis())
        {
            binder << getValueOfWis();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCha())
        {
            binder << getValueOfCha();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFortitude())
        {
            binder << getValueOfFortitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getReflex())
        {
            binder << getValueOfReflex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getWill())
        {
            binder << getValueOfWill();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getRolledhp())
        {
            binder << getValueOfRolledhp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getXp())
        {
            binder << getValueOfXp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getLoad())
        {
            binder << getValueOfLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Player::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    if(dirtyFlag_[15])
    {
        ret.push_back(getColumnName(15));
    }
    if(dirtyFlag_[16])
    {
        ret.push_back(getColumnName(16));
    }
    return ret;
}

void Player::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getName())
        {
            binder << getValueOfName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRace())
        {
            binder << getValueOfRace();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getClass())
        {
            binder << getValueOfClass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getArmorclass())
        {
            binder << getValueOfArmorclass();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStr())
        {
            binder << getValueOfStr();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCon())
        {
            binder << getValueOfCon();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDex())
        {
            binder << getValueOfDex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getInt())
        {
            binder << getValueOfInt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getWis())
        {
            binder << getValueOfWis();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getCha())
        {
            binder << getValueOfCha();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFortitude())
        {
            binder << getValueOfFortitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getReflex())
        {
            binder << getValueOfReflex();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getWill())
        {
            binder << getValueOfWill();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getRolledhp())
        {
            binder << getValueOfRolledhp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[15])
    {
        if(getXp())
        {
            binder << getValueOfXp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[16])
    {
        if(getLoad())
        {
            binder << getValueOfLoad();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Player::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["Id"]=getValueOfId();
    }
    else
    {
        ret["Id"]=Json::Value();
    }
    if(getName())
    {
        ret["Name"]=getValueOfName();
    }
    else
    {
        ret["Name"]=Json::Value();
    }
    if(getRace())
    {
        ret["Race"]=getValueOfRace();
    }
    else
    {
        ret["Race"]=Json::Value();
    }
    if(getClass())
    {
        ret["Class"]=getValueOfClass();
    }
    else
    {
        ret["Class"]=Json::Value();
    }
    if(getArmorclass())
    {
        ret["ArmorClass"]=getValueOfArmorclass();
    }
    else
    {
        ret["ArmorClass"]=Json::Value();
    }
    if(getStr())
    {
        ret["Str"]=getValueOfStr();
    }
    else
    {
        ret["Str"]=Json::Value();
    }
    if(getCon())
    {
        ret["Con"]=getValueOfCon();
    }
    else
    {
        ret["Con"]=Json::Value();
    }
    if(getDex())
    {
        ret["Dex"]=getValueOfDex();
    }
    else
    {
        ret["Dex"]=Json::Value();
    }
    if(getInt())
    {
        ret["Int"]=getValueOfInt();
    }
    else
    {
        ret["Int"]=Json::Value();
    }
    if(getWis())
    {
        ret["Wis"]=getValueOfWis();
    }
    else
    {
        ret["Wis"]=Json::Value();
    }
    if(getCha())
    {
        ret["Cha"]=getValueOfCha();
    }
    else
    {
        ret["Cha"]=Json::Value();
    }
    if(getFortitude())
    {
        ret["Fortitude"]=getValueOfFortitude();
    }
    else
    {
        ret["Fortitude"]=Json::Value();
    }
    if(getReflex())
    {
        ret["Reflex"]=getValueOfReflex();
    }
    else
    {
        ret["Reflex"]=Json::Value();
    }
    if(getWill())
    {
        ret["Will"]=getValueOfWill();
    }
    else
    {
        ret["Will"]=Json::Value();
    }
    if(getRolledhp())
    {
        ret["RolledHp"]=getValueOfRolledhp();
    }
    else
    {
        ret["RolledHp"]=Json::Value();
    }
    if(getXp())
    {
        ret["Xp"]=getValueOfXp();
    }
    else
    {
        ret["Xp"]=Json::Value();
    }
    if(getLoad())
    {
        ret["Load"]=getValueOfLoad();
    }
    else
    {
        ret["Load"]=Json::Value();
    }
    return ret;
}

Json::Value Player::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 17)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getName())
            {
                ret[pMasqueradingVector[1]]=getValueOfName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRace())
            {
                ret[pMasqueradingVector[2]]=getValueOfRace();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getClass())
            {
                ret[pMasqueradingVector[3]]=getValueOfClass();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getArmorclass())
            {
                ret[pMasqueradingVector[4]]=getValueOfArmorclass();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStr())
            {
                ret[pMasqueradingVector[5]]=getValueOfStr();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCon())
            {
                ret[pMasqueradingVector[6]]=getValueOfCon();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDex())
            {
                ret[pMasqueradingVector[7]]=getValueOfDex();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getInt())
            {
                ret[pMasqueradingVector[8]]=getValueOfInt();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getWis())
            {
                ret[pMasqueradingVector[9]]=getValueOfWis();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getCha())
            {
                ret[pMasqueradingVector[10]]=getValueOfCha();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getFortitude())
            {
                ret[pMasqueradingVector[11]]=getValueOfFortitude();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getReflex())
            {
                ret[pMasqueradingVector[12]]=getValueOfReflex();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getWill())
            {
                ret[pMasqueradingVector[13]]=getValueOfWill();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getRolledhp())
            {
                ret[pMasqueradingVector[14]]=getValueOfRolledhp();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[15].empty())
        {
            if(getXp())
            {
                ret[pMasqueradingVector[15]]=getValueOfXp();
            }
            else
            {
                ret[pMasqueradingVector[15]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[16].empty())
        {
            if(getLoad())
            {
                ret[pMasqueradingVector[16]]=getValueOfLoad();
            }
            else
            {
                ret[pMasqueradingVector[16]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["Id"]=getValueOfId();
    }
    else
    {
        ret["Id"]=Json::Value();
    }
    if(getName())
    {
        ret["Name"]=getValueOfName();
    }
    else
    {
        ret["Name"]=Json::Value();
    }
    if(getRace())
    {
        ret["Race"]=getValueOfRace();
    }
    else
    {
        ret["Race"]=Json::Value();
    }
    if(getClass())
    {
        ret["Class"]=getValueOfClass();
    }
    else
    {
        ret["Class"]=Json::Value();
    }
    if(getArmorclass())
    {
        ret["ArmorClass"]=getValueOfArmorclass();
    }
    else
    {
        ret["ArmorClass"]=Json::Value();
    }
    if(getStr())
    {
        ret["Str"]=getValueOfStr();
    }
    else
    {
        ret["Str"]=Json::Value();
    }
    if(getCon())
    {
        ret["Con"]=getValueOfCon();
    }
    else
    {
        ret["Con"]=Json::Value();
    }
    if(getDex())
    {
        ret["Dex"]=getValueOfDex();
    }
    else
    {
        ret["Dex"]=Json::Value();
    }
    if(getInt())
    {
        ret["Int"]=getValueOfInt();
    }
    else
    {
        ret["Int"]=Json::Value();
    }
    if(getWis())
    {
        ret["Wis"]=getValueOfWis();
    }
    else
    {
        ret["Wis"]=Json::Value();
    }
    if(getCha())
    {
        ret["Cha"]=getValueOfCha();
    }
    else
    {
        ret["Cha"]=Json::Value();
    }
    if(getFortitude())
    {
        ret["Fortitude"]=getValueOfFortitude();
    }
    else
    {
        ret["Fortitude"]=Json::Value();
    }
    if(getReflex())
    {
        ret["Reflex"]=getValueOfReflex();
    }
    else
    {
        ret["Reflex"]=Json::Value();
    }
    if(getWill())
    {
        ret["Will"]=getValueOfWill();
    }
    else
    {
        ret["Will"]=Json::Value();
    }
    if(getRolledhp())
    {
        ret["RolledHp"]=getValueOfRolledhp();
    }
    else
    {
        ret["RolledHp"]=Json::Value();
    }
    if(getXp())
    {
        ret["Xp"]=getValueOfXp();
    }
    else
    {
        ret["Xp"]=Json::Value();
    }
    if(getLoad())
    {
        ret["Load"]=getValueOfLoad();
    }
    else
    {
        ret["Load"]=Json::Value();
    }
    return ret;
}

bool Player::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("Id"))
    {
        if(!validJsonOfField(0, "Id", pJson["Id"], err, true))
            return false;
    }
    if(pJson.isMember("Name"))
    {
        if(!validJsonOfField(1, "Name", pJson["Name"], err, true))
            return false;
    }
    if(pJson.isMember("Race"))
    {
        if(!validJsonOfField(2, "Race", pJson["Race"], err, true))
            return false;
    }
    if(pJson.isMember("Class"))
    {
        if(!validJsonOfField(3, "Class", pJson["Class"], err, true))
            return false;
    }
    if(pJson.isMember("ArmorClass"))
    {
        if(!validJsonOfField(4, "ArmorClass", pJson["ArmorClass"], err, true))
            return false;
    }
    if(pJson.isMember("Str"))
    {
        if(!validJsonOfField(5, "Str", pJson["Str"], err, true))
            return false;
    }
    if(pJson.isMember("Con"))
    {
        if(!validJsonOfField(6, "Con", pJson["Con"], err, true))
            return false;
    }
    if(pJson.isMember("Dex"))
    {
        if(!validJsonOfField(7, "Dex", pJson["Dex"], err, true))
            return false;
    }
    if(pJson.isMember("Int"))
    {
        if(!validJsonOfField(8, "Int", pJson["Int"], err, true))
            return false;
    }
    if(pJson.isMember("Wis"))
    {
        if(!validJsonOfField(9, "Wis", pJson["Wis"], err, true))
            return false;
    }
    if(pJson.isMember("Cha"))
    {
        if(!validJsonOfField(10, "Cha", pJson["Cha"], err, true))
            return false;
    }
    if(pJson.isMember("Fortitude"))
    {
        if(!validJsonOfField(11, "Fortitude", pJson["Fortitude"], err, true))
            return false;
    }
    if(pJson.isMember("Reflex"))
    {
        if(!validJsonOfField(12, "Reflex", pJson["Reflex"], err, true))
            return false;
    }
    if(pJson.isMember("Will"))
    {
        if(!validJsonOfField(13, "Will", pJson["Will"], err, true))
            return false;
    }
    if(pJson.isMember("RolledHp"))
    {
        if(!validJsonOfField(14, "RolledHp", pJson["RolledHp"], err, true))
            return false;
    }
    if(pJson.isMember("Xp"))
    {
        if(!validJsonOfField(15, "Xp", pJson["Xp"], err, true))
            return false;
    }
    if(pJson.isMember("Load"))
    {
        if(!validJsonOfField(16, "Load", pJson["Load"], err, true))
            return false;
    }
    else
    {
        err="The Load column cannot be null";
        return false;
    }
    return true;
}
bool Player::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 17)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[15].empty())
      {
          if(pJson.isMember(pMasqueradingVector[15]))
          {
              if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[16].empty())
      {
          if(pJson.isMember(pMasqueradingVector[16]))
          {
              if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[16] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Player::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("Id"))
    {
        if(!validJsonOfField(0, "Id", pJson["Id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("Name"))
    {
        if(!validJsonOfField(1, "Name", pJson["Name"], err, false))
            return false;
    }
    if(pJson.isMember("Race"))
    {
        if(!validJsonOfField(2, "Race", pJson["Race"], err, false))
            return false;
    }
    if(pJson.isMember("Class"))
    {
        if(!validJsonOfField(3, "Class", pJson["Class"], err, false))
            return false;
    }
    if(pJson.isMember("ArmorClass"))
    {
        if(!validJsonOfField(4, "ArmorClass", pJson["ArmorClass"], err, false))
            return false;
    }
    if(pJson.isMember("Str"))
    {
        if(!validJsonOfField(5, "Str", pJson["Str"], err, false))
            return false;
    }
    if(pJson.isMember("Con"))
    {
        if(!validJsonOfField(6, "Con", pJson["Con"], err, false))
            return false;
    }
    if(pJson.isMember("Dex"))
    {
        if(!validJsonOfField(7, "Dex", pJson["Dex"], err, false))
            return false;
    }
    if(pJson.isMember("Int"))
    {
        if(!validJsonOfField(8, "Int", pJson["Int"], err, false))
            return false;
    }
    if(pJson.isMember("Wis"))
    {
        if(!validJsonOfField(9, "Wis", pJson["Wis"], err, false))
            return false;
    }
    if(pJson.isMember("Cha"))
    {
        if(!validJsonOfField(10, "Cha", pJson["Cha"], err, false))
            return false;
    }
    if(pJson.isMember("Fortitude"))
    {
        if(!validJsonOfField(11, "Fortitude", pJson["Fortitude"], err, false))
            return false;
    }
    if(pJson.isMember("Reflex"))
    {
        if(!validJsonOfField(12, "Reflex", pJson["Reflex"], err, false))
            return false;
    }
    if(pJson.isMember("Will"))
    {
        if(!validJsonOfField(13, "Will", pJson["Will"], err, false))
            return false;
    }
    if(pJson.isMember("RolledHp"))
    {
        if(!validJsonOfField(14, "RolledHp", pJson["RolledHp"], err, false))
            return false;
    }
    if(pJson.isMember("Xp"))
    {
        if(!validJsonOfField(15, "Xp", pJson["Xp"], err, false))
            return false;
    }
    if(pJson.isMember("Load"))
    {
        if(!validJsonOfField(16, "Load", pJson["Load"], err, false))
            return false;
    }
    return true;
}
bool Player::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 17)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
      if(!pMasqueradingVector[15].empty() && pJson.isMember(pMasqueradingVector[15]))
      {
          if(!validJsonOfField(15, pMasqueradingVector[15], pJson[pMasqueradingVector[15]], err, false))
              return false;
      }
      if(!pMasqueradingVector[16].empty() && pJson.isMember(pMasqueradingVector[16]))
      {
          if(!validJsonOfField(16, pMasqueradingVector[16], pJson[pMasqueradingVector[16]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Player::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 15:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 16:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
